// Array of quotes
const quotes = [
    "The best way to get started is to quit talking and begin doing. – Walt Disney",
    "The pessimist sees difficulty in every opportunity. The optimist sees opportunity in every difficulty. – Winston Churchill",
    "Don’t let yesterday take up too much of today. – Will Rogers",
    "It’s not whether you get knocked down, it’s whether you get up. – Vince Lombardi"
    "The only way to do great work is to love what you do. – Steve Jobs"
"Success is not final, failure is not fatal: It is the courage to continue that counts. – Winston Churchill"
"You must be the change you wish to see in the world. – Mahatma Gandhi"
"In the middle of every difficulty lies opportunity. – Albert Einstein"
"What lies behind us and what lies before us are tiny matters compared to what lies within us. – Ralph Waldo Emerson"
"The only limit to our realization of tomorrow is our doubts of today. – Franklin D. Roosevelt"
"Do not wait to strike till the iron is hot, but make it hot by striking. – William Butler Yeats"
"The harder you work for something, the greater you’ll feel when you achieve it."
"You are never too old to set another goal or to dream a new dream. – C.S. Lewis"
"Believe you can and you're halfway there. – Theodore Roosevelt"
"Your time is limited, so don’t waste it living someone else’s life. – Steve Jobs"
"Success is not how high you have climbed, but how you make a positive difference to the world. – Roy T. Bennett"
"The future belongs to those who believe in the beauty of their dreams. – Eleanor Roosevelt"
"It always seems impossible until it's done. – Nelson Mandela"
"The only impossible journey is the one you never begin. – Tony Robbins"
"You miss 100% of the shots you don’t take. – Wayne Gretzky"
"The way to get started is to quit talking and begin doing. – Walt Disney"
"If you can dream it, you can do it. – Walt Disney"
"The purpose of life is not to be happy. It is to be useful, to be honorable, to be compassionate, to have it make some difference that you have lived and lived well. – Ralph Waldo Emerson"
"In the end, we only regret the chances we didn’t take."
"Everything you’ve ever wanted is on the other side of fear."
"The only thing standing between you and your goal is the story you keep telling yourself as to why you can’t achieve it. – Jordan Belfort"
"Do not go where the path may lead, go instead where there is no path and leave a trail. – Ralph Waldo Emerson"
"What you get by achieving your goals is not as important as what you become by achieving your goals. – Zig Ziglar"
"Hardships often prepare ordinary people for an extraordinary destiny. – C.S. Lewis"
"A journey of a thousand miles begins with a single step. – Lao Tzu"
"Everything has beauty, but not everyone sees it. – Confucius"
"The best revenge is massive success. – Frank Sinatra"
"A winner is a dreamer who never gives up. – Nelson Mandela"
"Opportunities don't happen, you create them. – Chris Grosser"
"Don't watch the clock; do what it does. Keep going. – Sam Levenson"
"Don't be pushed around by the fears in your mind. Be led by the dreams in your heart. – Roy T. Bennett"
"You are braver than you believe, stronger than you seem, and smarter than you think. – A.A. Milne"
"Life is 10% what happens to us and 90% how we react to it. – Charles R. Swindoll"
"Success usually comes to those who are too busy to be looking for it. – Henry David Thoreau"
"Life is what happens when you're busy making other plans. – John Lennon"
"The harder the battle, the sweeter the victory."
"Good things come to those who hustle."
"You don’t have to be great to start, but you have to start to be great. – Zig Ziglar"
"It’s not whether you get knocked down, it’s whether you get up. – Vince Lombardi"
"The only way to achieve the impossible is to believe it is possible. – Charles Kingsleigh"
"What you get by achieving your goals is not as important as what you become by achieving your goals."
"We may encounter many defeats but we must not be defeated. – Maya Angelou"
"You can’t cross the sea merely by standing and staring at the water. – Rabindranath Tagore"
"Don't limit your challenges. Challenge your limits."
"Start where you are. Use what you have. Do what you can. – Arthur Ashe"
"The road to success and the road to failure are almost exactly the same. – Colin R. Davis"
"Everything you can imagine is real. – Pablo Picasso"
"Your limitation—it's only your imagination."
"Push yourself, because no one else is going to do it for you."
"Great things never come from comfort zones."
"Dream it. Wish it. Do it."
"Success doesn’t just find you. You have to go out and get it. – Unknown"
"The harder you work for something, the greater you’ll feel when you achieve it."
"Dream bigger. Do bigger."
"Don’t stop when you’re tired. Stop when you’re done."
"Wake up with determination. Go to bed with satisfaction."
"Little things make big days."
"It’s going to be hard, but hard does not mean impossible."
"Don’t wait for opportunity. Create it."
"Sometimes we’re tested not to show our weaknesses, but to discover our strengths."
"The key to success is to focus on goals, not obstacles."
"Dream it. Believe it. Build it."
"Success doesn’t come from what you do occasionally, it comes from what you do consistently."
"You don’t have to be great to start, but you have to start to be great."
"The way to get started is to quit talking and begin doing. – Walt Disney"
"Act as if what you do makes a difference. It does. – William James"
"Success is the sum of small efforts, repeated day in and day out. – Robert Collier"
"The only place where success comes before work is in the dictionary. – Vidal Sassoon"
"Don’t wait for the perfect moment. Take the moment and make it perfect."
"I find that the harder I work, the more luck I seem to have. – Thomas Jefferson"
"When you feel like quitting, remember why you started."
"Success is the ability to go from one failure to another with no loss of enthusiasm. – Winston Churchill"
"Everything you’ve ever wanted is on the other side of fear."
"Do something today that your future self will thank you for."
"Don’t be afraid to give up the good to go for the great. – John D. Rockefeller"
"Challenges are what make life interesting. Overcoming them is what makes life meaningful. – Joshua J. Marine"
"The best way to predict the future is to create it. – Peter Drucker"
"Strive not to be a success, but rather to be of value. – Albert Einstein"
"I’ve learned that people will forget what you said, people will forget what you did, but people will never forget how you made them feel. – Maya Angelou"
"Keep your face always toward the sunshine—and shadows will fall behind you. – Walt Whitman"
"Limit your "always" and your "nevers." – Amy Poehler"
"Nothing is impossible. The word itself says “I’m possible!” – Audrey Hepburn"
"The future belongs to those who believe in the beauty of their dreams. – Eleanor Roosevelt"
"Keep going. Everything you need will come to you at the perfect time."
"Sometimes the hardest part isn’t letting go but learning to start over."
"If you’re going through hell, keep going. – Winston Churchill"
"The only limit to our realization of tomorrow is our doubts of today. – Franklin D. Roosevelt"
"Keep your head up. Keep your heart strong. – Ben Howard"
"You only fail when you stop trying."
"Do not wait to strike till the iron is hot, but make it hot by striking. – William Butler Yeats"
"You don’t have to be great to start, but you have to start to be great. – Zig Ziglar"
"Success is not the key to happiness. Happiness is the key to success. – Albert Schweitzer"
"Everything you’ve ever wanted is on the other side of fear."
"The only thing standing between you and your goal is the story you keep telling yourself."
"Success is not how high you have climbed, but how you make a positive difference to the world. – Roy T. Bennett"
];

// Function to display a new quote
function newQuote() {
    // Get a random index from the quotes array
    const randomIndex = Math.floor(Math.random() * quotes.length);
    
    // Update the quote text on the webpage, wrapping it in double quotes
    document.getElementById('quote').textContent = `"${quotes[randomIndex]}"`;
}

// Optional: Call newQuote when the page loads to show the first quote
window.onload = newQuote;


